name: Deploy Interiq

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.93.110.100
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          timeout: 120s
          command_timeout: 20m
          script: |

            set -e

            echo "Starting deployment"

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            node -v
            npm -v

            cd ~/ILS
            git pull origin main

            echo "Deploy backend"
            cd backend
            npm install
            pm2 restart interiq-backend || pm2 start server.js --name interiq-backend

            echo "Deploy client"
            cd ../interiq-client
            npm install
            npm run build
            rm -rf /var/www/interiq-client/*
            cp -r dist/* /var/www/interiq-client/

            echo "Deploy admin"
            cd ../interiq-admin
            npm install
            npm run build
            rm -rf /var/www/interiq-admin/*
            cp -r dist/* /var/www/interiq-admin/

            systemctl reload nginx

            echo "Deployment finished"